name: Build with maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '11' ] # 8, 11
        os: [ 'ubuntu-latest' ] #, 'macos-latest', 'windows-latest' ]
    name: Java ${{ matrix.Java }} on (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Get current UTC time
        id: date
        run: echo "::set-output name=date::$(TZ='UTC' date +'.%Y%m%dT%H%M%S')"
      - name: Update pom version
        run:
          sed -i s/-SNAPSHOT/${{ steps.date.outputs.date }}.java-${{ matrix.Java }}.${{ matrix.os }}/g pom.xml
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Copy build artifact
        run: mkdir artifacts && cp target/*.jar artifacts
      - name: Upload jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: $artifactId-java${{ matrix.Java }}
          path: artifacts/
          retention-days: 3
